[package]
authors = ["Andreas <shadowstep7@gmail.com>"]
name = "handlebars-vdom-derive"
version = "0.1.0"

[dependencies]
globset = "0.2.1"
quote = "0.3.15"
syn = "0.11.11"
walkdir = "2.0.1"

[lib]
proc-macro = true
