[package]
authors = ["Andreas <shadowstep7@gmail.com>"]
name = "handlebars_vdom_parser"
version = "0.1.0"

[dependencies]
combine = "2.5.2"
html5ever = "0.21.0"
markup5ever = "0.6.2"
typed-arena = "1.3.0"

[dependencies.clippy]
optional = true
version = "*"

[features]
default = []
